-- Generated by npm run db:build from 01-schema.sql.
-- 为已有数据库补充中文表和字段备注；版本标记确保只执行一次。
SET NAMES utf8mb4;
SET @tzme_comments_done = EXISTS (SELECT 1 FROM app_migrations WHERE id = '2026-10-column-comments-v1');

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `app_migrations`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''迁移标识，记录已执行的初始化或升级脚本'',
  MODIFY COLUMN applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT ''迁移执行时间'',
  COMMENT=''数据库初始化与版本迁移记录''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `site_content`
  MODIFY COLUMN db_id BIGINT NOT NULL AUTO_INCREMENT COMMENT ''数据库自增主键'',
  MODIFY COLUMN id VARCHAR(255) NOT NULL COMMENT ''内容业务标识，用于接口和详情页地址'',
  MODIFY COLUMN type VARCHAR(255) NOT NULL COMMENT ''内容类型：products 产品，articles 新闻'',
  MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT ''标题，兼容旧版英文数据'',
  MODIFY COLUMN title_en VARCHAR(255) COMMENT ''英文标题'',
  MODIFY COLUMN title_zh VARCHAR(255) COMMENT ''中文标题'',
  MODIFY COLUMN category VARCHAR(255) COMMENT ''分类名称，兼容旧版英文数据'',
  MODIFY COLUMN category_en VARCHAR(255) COMMENT ''英文分类名称，用于分类展示和新闻筛选'',
  MODIFY COLUMN category_zh VARCHAR(255) COMMENT ''中文分类名称'',
  MODIFY COLUMN industry VARCHAR(255) COMMENT ''首选行业标识，关联 industries.id，兼容旧版单行业数据'',
  MODIFY COLUMN industry_ids VARCHAR(2000) COMMENT ''产品关联行业标识列表，以逗号分隔，支持多个行业'',
  MODIFY COLUMN summary VARCHAR(3000) COMMENT ''摘要，兼容旧版英文数据'',
  MODIFY COLUMN summary_en VARCHAR(3000) COMMENT ''英文摘要或产品简介'',
  MODIFY COLUMN summary_zh VARCHAR(3000) COMMENT ''中文摘要或产品简介'',
  MODIFY COLUMN image VARCHAR(255) COMMENT ''封面图片地址，可使用站内路径或完整网址'',
  MODIFY COLUMN status VARCHAR(255) COMMENT ''发布状态：published 已发布，draft 草稿，deleted 已删除'',
  MODIFY COLUMN date DATE COMMENT ''发布日期，新闻列表按此日期倒序展示'',
  MODIFY COLUMN content LONGTEXT COMMENT ''正文，兼容旧版英文数据'',
  MODIFY COLUMN content_en LONGTEXT COMMENT ''英文详情正文，新闻使用富文本 HTML'',
  MODIFY COLUMN content_zh LONGTEXT COMMENT ''中文详情正文，新闻使用富文本 HTML'',
  MODIFY COLUMN features_en TEXT COMMENT ''英文产品特点，每行一条'',
  MODIFY COLUMN features_zh TEXT COMMENT ''中文产品特点，每行一条'',
  MODIFY COLUMN specifications_en TEXT COMMENT ''英文产品参数，每行一项，参数名与数值用冒号分隔'',
  MODIFY COLUMN specifications_zh TEXT COMMENT ''中文产品参数，每行一项，参数名与数值用冒号分隔'',
  MODIFY COLUMN show_on_home BIT(1) COMMENT ''产品是否在首页解决方案展示：1 是，0 否'',
  MODIFY COLUMN home_order INT COMMENT ''产品首页展示顺序，数值越小越靠前'',
  COMMENT=''产品信息与新闻资讯，中英文内容''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `industries`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''行业业务标识，供产品关联和官网筛选使用'',
  MODIFY COLUMN title_en VARCHAR(255) NOT NULL COMMENT ''英文行业名称'',
  MODIFY COLUMN title_zh VARCHAR(255) NOT NULL COMMENT ''中文行业名称'',
  MODIFY COLUMN subtitle_en VARCHAR(1000) COMMENT ''英文行业简短说明'',
  MODIFY COLUMN subtitle_zh VARCHAR(1000) COMMENT ''中文行业简短说明'',
  MODIFY COLUMN sort_order INT NOT NULL COMMENT ''行业展示顺序，数值越小越靠前'',
  MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT ''发布状态：published 已发布，draft 草稿，deleted 已删除'',
  COMMENT=''服务行业，关联首页行业展示和产品筛选''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `certifications`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''资质认证业务标识'',
  MODIFY COLUMN title_en VARCHAR(255) NOT NULL COMMENT ''英文资质认证名称'',
  MODIFY COLUMN title_zh VARCHAR(255) NOT NULL COMMENT ''中文资质认证名称'',
  MODIFY COLUMN issuer_en VARCHAR(255) COMMENT ''英文颁发机构名称'',
  MODIFY COLUMN issuer_zh VARCHAR(255) COMMENT ''中文颁发机构名称'',
  MODIFY COLUMN summary_en VARCHAR(3000) COMMENT ''英文资质认证说明'',
  MODIFY COLUMN summary_zh VARCHAR(3000) COMMENT ''中文资质认证说明'',
  MODIFY COLUMN certificate_no VARCHAR(255) COMMENT ''证书编号'',
  MODIFY COLUMN issued_at DATE COMMENT ''证书颁发日期'',
  MODIFY COLUMN expires_at DATE COMMENT ''证书到期日期'',
  MODIFY COLUMN image VARCHAR(500) COMMENT ''证书图片地址，可使用站内路径或完整网址'',
  MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT ''发布状态：published 已发布，draft 草稿，deleted 已删除'',
  MODIFY COLUMN sort_order INT NOT NULL COMMENT ''资质认证展示顺序，数值越小越靠前'',
  COMMENT=''企业资质认证，中英文证书信息''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `projects`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''项目业务标识，用于接口和项目详情页地址'',
  MODIFY COLUMN title_en VARCHAR(255) NOT NULL COMMENT ''英文项目名称'',
  MODIFY COLUMN title_zh VARCHAR(255) NOT NULL COMMENT ''中文项目名称'',
  MODIFY COLUMN industry_en VARCHAR(255) COMMENT ''英文项目行业标签'',
  MODIFY COLUMN industry_zh VARCHAR(255) COMMENT ''中文项目行业标签'',
  MODIFY COLUMN location_en VARCHAR(255) COMMENT ''英文项目所在国家或地区'',
  MODIFY COLUMN location_zh VARCHAR(255) COMMENT ''中文项目所在国家或地区'',
  MODIFY COLUMN image_alt_en VARCHAR(255) COMMENT ''英文封面图片替代文字，供屏幕阅读器使用'',
  MODIFY COLUMN image_alt_zh VARCHAR(255) COMMENT ''中文封面图片替代文字，供屏幕阅读器使用'',
  MODIFY COLUMN summary_en VARCHAR(3000) COMMENT ''英文项目摘要'',
  MODIFY COLUMN summary_zh VARCHAR(3000) COMMENT ''中文项目摘要'',
  MODIFY COLUMN content_en LONGTEXT COMMENT ''英文项目详情正文，使用富文本 HTML'',
  MODIFY COLUMN content_zh LONGTEXT COMMENT ''中文项目详情正文，使用富文本 HTML'',
  MODIFY COLUMN capacity_label_en VARCHAR(255) COMMENT ''英文处理能力指标名称'',
  MODIFY COLUMN capacity_label_zh VARCHAR(255) COMMENT ''中文处理能力指标名称'',
  MODIFY COLUMN capacity_en VARCHAR(255) COMMENT ''英文处理能力数值及单位'',
  MODIFY COLUMN capacity_zh VARCHAR(255) COMMENT ''中文处理能力数值及单位'',
  MODIFY COLUMN technology_label_en VARCHAR(255) COMMENT ''英文技术方案指标名称'',
  MODIFY COLUMN technology_label_zh VARCHAR(255) COMMENT ''中文技术方案指标名称'',
  MODIFY COLUMN technology_en VARCHAR(255) COMMENT ''英文技术方案或设备名称'',
  MODIFY COLUMN technology_zh VARCHAR(255) COMMENT ''中文技术方案或设备名称'',
  MODIFY COLUMN scope_label_en VARCHAR(255) COMMENT ''英文供货范围指标名称'',
  MODIFY COLUMN scope_label_zh VARCHAR(255) COMMENT ''中文供货范围指标名称'',
  MODIFY COLUMN scope_en VARCHAR(255) COMMENT ''英文供货范围说明'',
  MODIFY COLUMN scope_zh VARCHAR(255) COMMENT ''中文供货范围说明'',
  MODIFY COLUMN image VARCHAR(500) COMMENT ''项目封面图片地址，可使用站内路径或完整网址'',
  MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT ''发布状态：published 已发布，draft 草稿，deleted 已删除'',
  MODIFY COLUMN sort_order INT NOT NULL COMMENT ''项目列表展示顺序，数值越小越靠前'',
  MODIFY COLUMN show_on_home BIT(1) NOT NULL COMMENT ''项目是否在首页精选项目展示：1 是，0 否'',
  MODIFY COLUMN home_order INT NOT NULL COMMENT ''项目首页展示顺序，数值越小越靠前'',
  COMMENT=''真实项目，中英文卡片信息与富文本详情''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `site_inquiries`
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT ''咨询记录自增主键'',
  MODIFY COLUMN name VARCHAR(255) COMMENT ''联系人姓名'',
  MODIFY COLUMN company VARCHAR(255) COMMENT ''客户公司名称'',
  MODIFY COLUMN country VARCHAR(255) COMMENT ''客户所在国家或地区'',
  MODIFY COLUMN email VARCHAR(255) COMMENT ''联系人邮箱'',
  MODIFY COLUMN phone VARCHAR(255) COMMENT ''联系人电话'',
  MODIFY COLUMN industry VARCHAR(255) COMMENT ''客户填写的所属行业'',
  MODIFY COLUMN requirements VARCHAR(6000) COMMENT ''客户提交的项目需求'',
  MODIFY COLUMN status VARCHAR(255) COMMENT ''咨询处理状态：new 待联系，contacted 已联系'',
  MODIFY COLUMN created_at DATETIME(6) COMMENT ''咨询提交时间'',
  COMMENT=''官网客户咨询与处理状态''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `home_global_settings`
  MODIFY COLUMN id BIGINT NOT NULL COMMENT ''全球业务配置主键，当前固定为 1'',
  MODIFY COLUMN configuration LONGTEXT NOT NULL COMMENT ''全球业务配置 JSON，包含中英文文案、地图点位、统计和跳转按钮'',
  COMMENT=''首页与关于我们共用的全球业务配置''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `site_settings`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''官网配置标识，website 表示网站基础配置'',
  MODIFY COLUMN configuration LONGTEXT NOT NULL COMMENT ''官网基础配置 JSON，包含多语言文案、图片地址、公司统计、联系方式和地图选项'',
  COMMENT=''官网多语言文案与基础展示配置''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

INSERT INTO app_migrations (id) SELECT '2026-10-column-comments-v1' WHERE NOT EXISTS (SELECT 1 FROM app_migrations WHERE id = '2026-10-column-comments-v1');
