-- Generated by npm run db:build from 01-schema.sql.
-- 为已有数据库补充中文表和字段备注；版本标记确保只执行一次。
SET NAMES utf8mb4;
SET @tzme_comments_done = EXISTS (SELECT 1 FROM app_migrations WHERE id = '2026-10-column-comments-v1');

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `app_migrations`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''迁移标识，记录已执行的初始化或升级脚本'',
  MODIFY COLUMN applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT ''迁移执行时间'',
  COMMENT=''数据库初始化与版本迁移记录''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `site_content`
  MODIFY COLUMN db_id BIGINT NOT NULL AUTO_INCREMENT COMMENT ''数据库自增主键'',
  MODIFY COLUMN id VARCHAR(255) NOT NULL COMMENT ''内容业务标识，用于接口和详情页地址'',
  MODIFY COLUMN type VARCHAR(255) NOT NULL COMMENT ''内容类型：products 产品，articles 新闻'',
  MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT ''标题，兼容旧版英文数据'',
  MODIFY COLUMN title_en VARCHAR(255) COMMENT ''英文标题'',
  MODIFY COLUMN title_zh VARCHAR(255) COMMENT ''中文标题'',
  MODIFY COLUMN category VARCHAR(255) COMMENT ''分类名称，兼容旧版英文数据'',
  MODIFY COLUMN category_en VARCHAR(255) COMMENT ''英文分类名称，用于分类展示和新闻筛选'',
  MODIFY COLUMN category_zh VARCHAR(255) COMMENT ''中文分类名称'',
  MODIFY COLUMN industry VARCHAR(255) COMMENT ''首选行业标识，关联 industries.id，兼容旧版单行业数据'',
  MODIFY COLUMN industry_ids VARCHAR(2000) COMMENT ''产品关联行业标识列表，以逗号分隔，支持多个行业'',
  MODIFY COLUMN summary VARCHAR(3000) COMMENT ''摘要，兼容旧版英文数据'',
  MODIFY COLUMN summary_en VARCHAR(3000) COMMENT ''英文摘要或产品简介'',
  MODIFY COLUMN summary_zh VARCHAR(3000) COMMENT ''中文摘要或产品简介'',
  MODIFY COLUMN image VARCHAR(255) COMMENT ''封面图片地址，可使用站内路径或完整网址'',
  MODIFY COLUMN status VARCHAR(255) COMMENT ''发布状态：published 已发布，draft 草稿，deleted 已删除'',
  MODIFY COLUMN date DATE COMMENT ''发布日期，新闻列表按此日期倒序展示'',
  MODIFY COLUMN content LONGTEXT COMMENT ''正文，兼容旧版英文数据'',
  MODIFY COLUMN content_en LONGTEXT COMMENT ''英文详情正文，新闻使用富文本 HTML'',
  MODIFY COLUMN content_zh LONGTEXT COMMENT ''中文详情正文，新闻使用富文本 HTML'',
  MODIFY COLUMN features_en TEXT COMMENT ''英文产品特点，每行一条'',
  MODIFY COLUMN features_zh TEXT COMMENT ''中文产品特点，每行一条'',
  MODIFY COLUMN specifications_en TEXT COMMENT ''英文产品参数，每行一项，参数名与数值用冒号分隔'',
  MODIFY COLUMN specifications_zh TEXT COMMENT ''中文产品参数，每行一项，参数名与数值用冒号分隔'',
  MODIFY COLUMN show_on_home BIT(1) COMMENT ''产品是否在首页解决方案展示：1 是，0 否'',
  MODIFY COLUMN home_order INT COMMENT ''产品首页展示顺序，数值越小越靠前'',
  COMMENT=''产品信息与新闻资讯，中英文内容''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `industries`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''行业业务标识，供产品关联和官网筛选使用'',
  MODIFY COLUMN title_en VARCHAR(255) NOT NULL COMMENT ''英文行业名称'',
  MODIFY COLUMN title_zh VARCHAR(255) NOT NULL COMMENT ''中文行业名称'',
  MODIFY COLUMN subtitle_en VARCHAR(1000) COMMENT ''英文行业简短说明'',
  MODIFY COLUMN subtitle_zh VARCHAR(1000) COMMENT ''中文行业简短说明'',
  MODIFY COLUMN icon VARCHAR(500) DEFAULT '''' COMMENT ''首页服务行业图标图片地址，中英文共用，支持预设图标或上传图片，空值使用通用图标'',
  MODIFY COLUMN sort_order INT NOT NULL COMMENT ''行业展示顺序，数值越小越靠前'',
  MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT ''发布状态：published 已发布，draft 草稿，deleted 已删除'',
  COMMENT=''服务行业，关联首页行业展示和产品筛选''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `certifications`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''资质认证业务标识'',
  MODIFY COLUMN title_en VARCHAR(255) NOT NULL COMMENT ''英文资质认证名称'',
  MODIFY COLUMN title_zh VARCHAR(255) NOT NULL COMMENT ''中文资质认证名称'',
  MODIFY COLUMN issuer_en VARCHAR(255) COMMENT ''英文颁发机构名称'',
  MODIFY COLUMN issuer_zh VARCHAR(255) COMMENT ''中文颁发机构名称'',
  MODIFY COLUMN summary_en VARCHAR(3000) COMMENT ''英文资质认证说明'',
  MODIFY COLUMN summary_zh VARCHAR(3000) COMMENT ''中文资质认证说明'',
  MODIFY COLUMN certificate_no VARCHAR(255) COMMENT ''证书编号'',
  MODIFY COLUMN issued_at DATE COMMENT ''证书颁发日期'',
  MODIFY COLUMN expires_at DATE COMMENT ''证书到期日期'',
  MODIFY COLUMN image VARCHAR(500) COMMENT ''证书图片地址，可使用站内路径或完整网址'',
  MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT ''发布状态：published 已发布，draft 草稿，deleted 已删除'',
  MODIFY COLUMN sort_order INT NOT NULL COMMENT ''资质认证展示顺序，数值越小越靠前'',
  COMMENT=''企业资质认证，中英文证书信息''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `projects`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''项目业务标识，用于接口和项目详情页地址'',
  MODIFY COLUMN title_en VARCHAR(255) NOT NULL COMMENT ''英文项目名称'',
  MODIFY COLUMN title_zh VARCHAR(255) NOT NULL COMMENT ''中文项目名称'',
  MODIFY COLUMN industry_en VARCHAR(255) COMMENT ''英文项目行业标签'',
  MODIFY COLUMN industry_zh VARCHAR(255) COMMENT ''中文项目行业标签'',
  MODIFY COLUMN location_en VARCHAR(255) COMMENT ''英文项目所在国家或地区'',
  MODIFY COLUMN location_zh VARCHAR(255) COMMENT ''中文项目所在国家或地区'',
  MODIFY COLUMN image_alt_en VARCHAR(255) COMMENT ''英文封面图片替代文字，供屏幕阅读器使用'',
  MODIFY COLUMN image_alt_zh VARCHAR(255) COMMENT ''中文封面图片替代文字，供屏幕阅读器使用'',
  MODIFY COLUMN summary_en VARCHAR(3000) COMMENT ''英文项目摘要'',
  MODIFY COLUMN summary_zh VARCHAR(3000) COMMENT ''中文项目摘要'',
  MODIFY COLUMN content_en LONGTEXT COMMENT ''英文项目详情正文，使用富文本 HTML'',
  MODIFY COLUMN content_zh LONGTEXT COMMENT ''中文项目详情正文，使用富文本 HTML'',
  MODIFY COLUMN capacity_label_en VARCHAR(255) COMMENT ''英文处理能力指标名称'',
  MODIFY COLUMN capacity_label_zh VARCHAR(255) COMMENT ''中文处理能力指标名称'',
  MODIFY COLUMN capacity_en VARCHAR(255) COMMENT ''英文处理能力数值及单位'',
  MODIFY COLUMN capacity_zh VARCHAR(255) COMMENT ''中文处理能力数值及单位'',
  MODIFY COLUMN technology_label_en VARCHAR(255) COMMENT ''英文技术方案指标名称'',
  MODIFY COLUMN technology_label_zh VARCHAR(255) COMMENT ''中文技术方案指标名称'',
  MODIFY COLUMN technology_en VARCHAR(255) COMMENT ''英文技术方案或设备名称'',
  MODIFY COLUMN technology_zh VARCHAR(255) COMMENT ''中文技术方案或设备名称'',
  MODIFY COLUMN scope_label_en VARCHAR(255) COMMENT ''英文供货范围指标名称'',
  MODIFY COLUMN scope_label_zh VARCHAR(255) COMMENT ''中文供货范围指标名称'',
  MODIFY COLUMN scope_en VARCHAR(255) COMMENT ''英文供货范围说明'',
  MODIFY COLUMN scope_zh VARCHAR(255) COMMENT ''中文供货范围说明'',
  MODIFY COLUMN image VARCHAR(500) COMMENT ''项目封面图片地址，可使用站内路径或完整网址'',
  MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT ''发布状态：published 已发布，draft 草稿，deleted 已删除'',
  MODIFY COLUMN sort_order INT NOT NULL COMMENT ''项目列表展示顺序，数值越小越靠前'',
  MODIFY COLUMN show_on_home BIT(1) NOT NULL COMMENT ''项目是否在首页精选项目展示：1 是，0 否'',
  MODIFY COLUMN home_order INT NOT NULL COMMENT ''项目首页展示顺序，数值越小越靠前'',
  COMMENT=''真实项目，中英文卡片信息与富文本详情''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `site_analytics_events`
  MODIFY COLUMN id CHAR(36) NOT NULL COMMENT ''埋点事件唯一标识，重复上报按此标识去重'',
  MODIFY COLUMN visitor_id CHAR(36) NOT NULL COMMENT ''匿名访客标识，同一浏览器本地保存，不包含客户身份'',
  MODIFY COLUMN session_id CHAR(36) NOT NULL COMMENT ''匿名访问会话标识，连续三十分钟无操作后重新生成'',
  MODIFY COLUMN event_name VARCHAR(32) NOT NULL COMMENT ''事件名称，包含浏览、停留、点击、筛选和咨询转化'',
  MODIFY COLUMN page_path VARCHAR(500) NOT NULL COMMENT ''官网页面路径，不保存查询参数和锚点'',
  MODIFY COLUMN page_key VARCHAR(32) NOT NULL COMMENT ''页面类型，首页、列表页及产品项目新闻详情页'',
  MODIFY COLUMN locale VARCHAR(20) NOT NULL COMMENT ''事件发生时的页面语言代码'',
  MODIFY COLUMN device VARCHAR(16) NOT NULL COMMENT ''设备类型：desktop 桌面、tablet 平板、mobile 手机'',
  MODIFY COLUMN referrer_host VARCHAR(255) NOT NULL COMMENT ''首次访问来源域名，直接访问记录为 direct，不保存完整链接'',
  MODIFY COLUMN target VARCHAR(255) NOT NULL COMMENT ''操作目标业务标识，不保存咨询内容及联系方式'',
  MODIFY COLUMN duration_seconds INT NOT NULL DEFAULT 0 COMMENT ''页面在前台可见的累计停留秒数，停留事件重复上报取最大值'',
  MODIFY COLUMN scroll_depth TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT ''页面最大滚动深度百分比，范围零至一百'',
  MODIFY COLUMN occurred_at DATETIME(3) NOT NULL COMMENT ''服务端接收事件时间，按 UTC 保存，后台按北京时间汇总'',
  COMMENT=''官网匿名访问埋点和咨询转化分析记录''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `site_inquiries`
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT ''咨询记录自增主键'',
  MODIFY COLUMN name VARCHAR(255) COMMENT ''联系人姓名'',
  MODIFY COLUMN company VARCHAR(255) COMMENT ''客户公司名称'',
  MODIFY COLUMN country VARCHAR(255) COMMENT ''客户所在国家或地区'',
  MODIFY COLUMN email VARCHAR(255) COMMENT ''联系人邮箱'',
  MODIFY COLUMN phone VARCHAR(255) COMMENT ''联系人电话'',
  MODIFY COLUMN industry VARCHAR(255) COMMENT ''客户填写的所属行业'',
  MODIFY COLUMN requirements VARCHAR(6000) COMMENT ''客户提交的项目需求'',
  MODIFY COLUMN status VARCHAR(255) COMMENT ''咨询处理状态：new 待联系，contacted 已联系，closed 已完成'',
  MODIFY COLUMN created_at DATETIME(6) COMMENT ''咨询提交时间'',
  MODIFY COLUMN locale VARCHAR(20) NOT NULL DEFAULT ''en'' COMMENT ''咨询提交时的界面语言'',
  MODIFY COLUMN notes TEXT COMMENT ''后台维护的内部跟进备注，最多 6000 字符'',
  MODIFY COLUMN mail_status VARCHAR(32) NOT NULL DEFAULT ''disabled'' COMMENT ''通知状态：disabled 关闭，pending 待发送，sending 发送中，sent 已发送，failed 失败'',
  MODIFY COLUMN mail_recipients TEXT COMMENT ''本条咨询创建或重试时选中的通知收件邮箱，逗号分隔'',
  MODIFY COLUMN mail_attempts INT NOT NULL DEFAULT 0 COMMENT ''本轮邮件通知已尝试发送次数，最多自动尝试三次'',
  MODIFY COLUMN mail_error VARCHAR(2000) NOT NULL DEFAULT '''' COMMENT ''通知发送失败说明，不包含账号密码'',
  MODIFY COLUMN mail_sent_at DATETIME(6) COMMENT ''邮件通知成功发送时间'',
  MODIFY COLUMN mail_next_attempt_at DATETIME(6) COMMENT ''下次发送时间，发送中表示任务锁定的截止时间'',
  COMMENT=''官网客户咨询与处理状态''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `inquiry_attachments`
  MODIFY COLUMN id VARCHAR(36) NOT NULL COMMENT ''附件随机 UUID，同时用于附件下载地址'',
  MODIFY COLUMN inquiry_id BIGINT COMMENT ''关联的咨询主键，未提交咨询时为空'',
  MODIFY COLUMN original_name VARCHAR(255) COMMENT ''上传文件的原始名称，用于后台展示及下载'',
  MODIFY COLUMN extension VARCHAR(20) COMMENT ''经过校验的文件扩展名'',
  MODIFY COLUMN size BIGINT NOT NULL COMMENT ''附件大小，单位为字节'',
  MODIFY COLUMN created_at DATETIME(6) COMMENT ''附件上传时间'',
  COMMENT=''咨询附件元数据，文件保存在上传目录的 inquiries 子目录''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `home_global_settings`
  MODIFY COLUMN id BIGINT NOT NULL COMMENT ''全球业务配置主键，当前固定为 1'',
  MODIFY COLUMN configuration LONGTEXT NOT NULL COMMENT ''全球业务配置 JSON，包含中英文文案、地图点位、统计和跳转按钮'',
  COMMENT=''首页与关于我们共用的全球业务配置''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

SET @tzme_comments_sql = IF(@tzme_comments_done, 'SELECT 1', 'ALTER TABLE `site_settings`
  MODIFY COLUMN id VARCHAR(100) NOT NULL COMMENT ''官网配置标识：website 网站基础配置，contact 联系与咨询配置，capabilities 首页能力配置'',
  MODIFY COLUMN configuration LONGTEXT NOT NULL COMMENT ''配置 JSON：website 多语言文案与图片，contact 联系、咨询和私有邮件配置，capabilities 中英文能力文案、流程步骤及图标'',
  COMMENT=''官网多语言文案与基础展示配置''');
PREPARE tzme_comments_statement FROM @tzme_comments_sql;
EXECUTE tzme_comments_statement;
DEALLOCATE PREPARE tzme_comments_statement;

INSERT INTO app_migrations (id) SELECT '2026-10-column-comments-v1' WHERE NOT EXISTS (SELECT 1 FROM app_migrations WHERE id = '2026-10-column-comments-v1');
