-- Generated by npm run db:build. Add industry icons and preserve later admin edits.
SET NAMES utf8mb4;
SET @tzme_industry_icon_sql = IF(EXISTS (SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='industries' AND COLUMN_NAME='icon'), 'SELECT 1', 'ALTER TABLE industries ADD COLUMN icon VARCHAR(500) DEFAULT '''' COMMENT ''首页服务行业图标图片地址，中英文共用，支持预设图标或上传图片，空值使用通用图标''');
PREPARE tzme_industry_icon_statement FROM @tzme_industry_icon_sql;
EXECUTE tzme_industry_icon_statement;
DEALLOCATE PREPARE tzme_industry_icon_statement;
START TRANSACTION;
SET @tzme_industry_icons_done = EXISTS (SELECT 1 FROM app_migrations WHERE id='2026-10-industry-icons-v1');
UPDATE industries SET icon=CONVERT(0x2f6173736574732f696e6475737472792d69636f6e732f6d696e696e672e737667 USING utf8mb4) COLLATE utf8mb4_unicode_ci WHERE id=CONVERT(0x6d696e696e67 USING utf8mb4) COLLATE utf8mb4_unicode_ci AND COALESCE(icon, '')='' AND NOT @tzme_industry_icons_done;
UPDATE industries SET icon=CONVERT(0x2f6173736574732f696e6475737472792d69636f6e732f706f7274732e737667 USING utf8mb4) COLLATE utf8mb4_unicode_ci WHERE id=CONVERT(0x706f727473 USING utf8mb4) COLLATE utf8mb4_unicode_ci AND COALESCE(icon, '')='' AND NOT @tzme_industry_icons_done;
UPDATE industries SET icon=CONVERT(0x2f6173736574732f696e6475737472792d69636f6e732f6d6574616c6c757267792e737667 USING utf8mb4) COLLATE utf8mb4_unicode_ci WHERE id=CONVERT(0x6d6574616c6c75726779 USING utf8mb4) COLLATE utf8mb4_unicode_ci AND COALESCE(icon, '')='' AND NOT @tzme_industry_icons_done;
UPDATE industries SET icon=CONVERT(0x2f6173736574732f696e6475737472792d69636f6e732f656e657267792e737667 USING utf8mb4) COLLATE utf8mb4_unicode_ci WHERE id=CONVERT(0x656e65726779 USING utf8mb4) COLLATE utf8mb4_unicode_ci AND COALESCE(icon, '')='' AND NOT @tzme_industry_icons_done;
UPDATE industries SET icon=CONVERT(0x2f6173736574732f696e6475737472792d69636f6e732f636f6e737472756374696f6e2e737667 USING utf8mb4) COLLATE utf8mb4_unicode_ci WHERE id=CONVERT(0x636f6e737472756374696f6e USING utf8mb4) COLLATE utf8mb4_unicode_ci AND COALESCE(icon, '')='' AND NOT @tzme_industry_icons_done;
INSERT INTO app_migrations (id) SELECT '2026-10-industry-icons-v1' WHERE NOT EXISTS (SELECT 1 FROM app_migrations WHERE id='2026-10-industry-icons-v1');
COMMIT;
